repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: "\\.pot$"
    -   id: trailing-whitespace
        exclude: "\\.pot$"
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
