from .iter import iter, generator
from .lib_augmenting import interpose, pad, pad_with, append, insert
from .lib_basic import (
    cons,
    uncons,
    first,
    second,
    nth,
    find,
    last,
    only,
    is_empty,
    length,
    consume,
)
from .lib_creation import cycle, iterate, repeat, repeatedly, singleton, unfold, nums
from .lib_grouping import (
    group_by,
    chunks,
    chunks_by,
    window,
    pairs,
    partition,
    distribute,
)
from .lib_reducers import (
    fold,
    reduce,
    scan,
    acc,
    reduce_by,
    fold_by,
    fold_together,
    reduce_together,
    scan_together,
    acc_together,
    product,
    products,
    sum,
    sums,
    all_by,
    any_by,
    top_k,
)
from .lib_selecting import (
    filter,
    remove,
    separate,
    drop,
    rdrop,
    take,
    rtake,
    unique,
    dedupe,
    converge,
)
from .lib_transforming import map, zip_map
from .lib_combining import concat, interleave, zip_aligned, merge_sorted, join, diff

__all__ = [
    # Core
    "iter",
    "generator",
    # Basic
    "cons",
    "uncons",
    "first",
    "second",
    "nth",
    "find",
    "only",
    "last",
    "is_empty",
    "length",
    "consume",
    # Creation
    "cycle",
    "iterate",
    "repeat",
    "repeatedly",
    "singleton",
    "unfold",
    "nums",
    # Selection
    "filter",
    "remove",
    "separate",
    "drop",
    "rdrop",
    "take",
    "rtake",
    "unique",
    "dedupe",
    "converge",
    # Reducers
    "fold",
    "reduce",
    "scan",
    "acc",
    "reduce_by",
    "fold_by",
    "fold_together",
    "reduce_together",
    "scan_together",
    "acc_together",
    "product",
    "products",
    "sum",
    "sums",
    "all_by",
    "any_by",
    "top_k",
    # Grouping
    "group_by",
    "chunks",
    "chunks_by",
    "window",
    "pairs",
    "partition",
    "distribute",
    # Transforming
    "map",
    "zip_map",
    # Augmenting
    "interpose",
    "pad",
    "pad_with",
    "append",
    "insert",
    # Combining
    "concat",
    "interleave",
    "zip_aligned",
    "merge_sorted",
    "join",
    "diff",
]
